In [9]:
# 1

import math

C = 50
H = 30

D = input("Enter the values with comma in-between.")
D = [int(i) for i in D.split(',')]

for value in D:
    Q = math.sqrt( (2*C* value)/ H)
    print(int(Q))

Enter the values with comma in-between.100,150,180
18
22
24


In [10]:
# 2

import numpy as np

X = int(input("Enter a number for X"))
Y = int(input("Enter a number for Y"))

result = np.zeros((X,Y))

for i in range(X):
    for j in range(Y):
        result[i,j] = i*j

print(result)

Enter a number for X3
Enter a number for Y5
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


In [20]:
# 3

my_str = input("enter the words")
my_list = [i for i in my_str.split(",")]

my_list.sort()

print(", ".join(my_list))

enter the wordswithout,hello,bag,world
bag, hello, without, world


In [27]:
# 4

my_str = input("enter a string")
my_set = set([i for i in my_str.split()])

my_set = sorted(my_set)

print(" ".join(my_set))

enter a stringhello world and practice makes perfect and hello world again
again and hello makes perfect practice world


In [28]:
# 5

my_str = input("enter a string")

letter = 0
digit = 0

for i in my_str:
    if i.isdigit():
        digit+=1
    elif i.isalpha():
        letter+=1

print("LETTERS {}".format(letter))
print("DIGITS {}".format(digit))

enter a stringhello world! 123
LETTERS 10
DIGITS 3


In [38]:
# 6
import re

passwords = input("Enter the passwords")
pw_list = [i for i in passwords.split(",")]

check = 0

for pw in pw_list:
    if len(pw) >= 6 and len(pw) <= 12:
        if not re.search("[a-z]", pw):
            break
        elif not re.search("[A-Z]", pw):
            break
        elif not re.search("[0-9]",pw):
            break
        elif not re.search("[$#@]",pw):
            break
        else:
            print(pw)
        
    else: 
        continue
        

Enter the passwordsABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1
