In [16]:
# 1. find sum of array

import numpy as np
array_a = np.random.randn(1,10).reshape((2,5))
print(array_a)

def sum_of_array(arr):
    sum1 = 0
    for i in range(len(arr)):
        for j in range(arr.shape[1]):
            sum1+= arr[i][j]
    
    return sum1

sum_of_array(array_a)

[[-0.65649609 -0.66259501 -1.50931803 -0.81490949  0.30028862]
 [-1.89898142 -1.10393515 -1.90071809  0.24945884 -0.96713409]]


-8.964339899696926

In [18]:
# 2. find largest element in an array

array_a = np.random.randn(10).reshape((2,5))* 10
print(array_a)

def max_element(arr):
    max_ele = 0
    for i in range(len(arr)):
        for j in range(arr.shape[1]):
            if arr[i][j]>max_ele:
                max_ele = arr[i][j]
    return max_ele
    
max_element(array_a)

[[  3.80857376  -9.79178369 -13.48314776  -1.77227713  -3.48125682]
 [ -2.06556906  -6.08900967 -18.2167542  -10.46749469   1.4034306 ]]


3.8085737572620855

In [38]:
# 3. Array rotation

array_a = np.random.randint(1,20,5)
print("The original array is:\n{}\n".format(array_a))

n = int(input("enter a number between 1 and 5 for number of places to rotate.\n"))

def rotate(arr, n):    
    for i in range(n):
        temp = arr[0]
        for j in range(len(arr)-1):
            arr[j] = arr[j+1]
        arr[-1] = temp
    print("\nThe rotated array is:\n{}".format(arr))

rotate(array_a, n)
    

The original array is:
[19  9 12 11  2]

enter a number between 1 and 5 for number of places to rotate.
3

The rotated array is:
[11  2 19  9 12]


In [68]:
# 4. Split the array and add the first part to the end

array_a = np.random.randint(1,20,10)
print("The original array is:\n{}\n".format(array_a))

n = int(input("enter a number between 1 and 9 for number of elements to split.\n"))

def split_and_append(arr, n):
    temp_arr = arr.copy()[:n]
    arr1 = np.delete(arr, [i for i in range(n)])
    result = np.concatenate((arr1, temp_arr), axis = 0)
    print("\nThe revised array is:\n{}".format(result))

split_and_append(array_a, n)    


The original array is:
[14 12 11 16 16 10 13 13  5  4]

enter a number between 1 and 9 for number of elements to split.
2

The revised array is:
[11 16 16 10 13 13  5  4 14 12]


In [89]:
# 5. Checking if Monotonic

array_a = [1,2,2,6]
array_b = [10,5,4,1]
array_c = [-1,0,-10,20]

def monotonic_check(arr):
    check = 0
    length = len(arr)
    
    if arr[0]>=arr[1]:
        for i in range(1, length-1):
            if arr[i] < arr[i+1]:
                print("Not Monotonic")
                break
            else: 
                check = 1
                
    elif arr[0]<=arr[1]:
        for i in range(1, length-1):
            if arr[i] > arr[i+1]:
                print("Not Monotonic")
                break
            else:
                check = 1
                
    if check == 1:
        print("Monotonic")
       
                
    
monotonic_check(array_a)
monotonic_check(array_b)
monotonic_check(array_c)
    
            
            
            
        

Monotonic
Monotonic
Not Monotonic
